feat: add math commands
ostis-ai/scn-latex-plugin pull request #34
Opened 2024-07-24 12:07 UTC by MakarenkoAI

2024-07-26 09:26 UTC, MksmOrlov requested changes
add test for math please

2024-07-29 08:05 UTC, NikitaZotov requested changes

2024-07-29 08:05 UTC, NikitaZotov commented on scn-macros-translator/src/grammar/SCnTex.interp
> +token literal names:
Remove C++ code, please

2024-07-29 16:02 UTC, MksmOrlov approved these changes

2024-07-29 16:05 UTC, MksmOrlov requested changes

2024-07-29 16:05 UTC, MksmOrlov commented on scn.sty
> +\newcommand{\scnqqi}[1]{''#1''}
do not edit this

2024-08-01 11:45 UTC, MksmOrlov approved these changes

2024-08-01 14:47 UTC, NikitaZotov approved these changes

2024-08-01 15:05 UTC, merged